import React from "react";
import Firstblog from "@/components/Firstblog";
import Otherblog from "@/components/Otherblog";
export const metadata = {
  title: "All Blog",
  // description: "Generated by create next app",
};
async function fetchBlogs() {
  const res = await fetch("https://weblog-bice.vercel.app/api/blog", {
    cache: "no-store",
  });

  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

const Blog = async () => {
  const blogs = await fetchBlogs();

  const firstBlog = blogs && blogs[0];
  const otherBlogs = blogs?.length > 0 && blogs.slice(1);
  return (
    <div>
      {blogs?.length > 0 ? (
        <>
          <div className="container">
            <h2 className="text-center my-10">
              <span className="text-primaryColor">Trending</span> Blog
            </h2>
            <Firstblog firstBlog={firstBlog} />
            <Otherblog otherBlogs={otherBlogs} />
          </div>
        </>
      ) : (
        <h3>No Blogs...</h3>
      )}
    </div>
  );
};

export default Blog;
