import React from "react";
import Loginform from "@/components/Login";

export const metadata = {
  title: "Login",
  // description: "Generated by create next app",
};

const Login = () => {
  return (
    <div>
      <Loginform />
    </div>
  );
};

export default Login;
