import React from "react";
import SignUpform from "@/components/SignUp";

export const metadata = {
  title: "SignUp",
  // description: "Generated by create next app",
};

const SignUp = () => {
  return (
    <div>
      <SignUpform />
    </div>
  );
};

export default SignUp;
